### ISSUE TITLE
Upsampler crashes on very short audio sequence

### ISSUE THREAD

**Issue by heebtob** [umjammer/vavi-sound#4]
I have a very short audio sequence with 13093 samples. It's a Linear PCM Wave with 44100 hz Mono 16bits. 
I'd like to upsample it to 48000 hz. 

It crashes at the following line because the result of the calculation is negative.

```
SSRC.java:1006
rawoutbuf.limit((int) (dbps * nch * (Math.floor((double) sumread * dfrq / sfrq) + 2 - sumwrite - delay)));

java.lang.IllegalArgumentException: null
	at java.nio.Buffer.limit(Buffer.java:275) ~[na:1.8.0_161]
	at vavi.sound.pcm.resampling.ssrc.SSRC$Upsampler.resample(SSRC.java:1006) ~[na:na]
	at vavi.sound.pcm.resampling.ssrc.SSRC.io(SSRC.java:2431) ~[na:na]
	at vavi.sound.pcm.resampling.ssrc.SSRCInputStream$1.run(SSRCInputStream.java:88) ~[na:na]
```

Are such short sequences generally not supported or is it a corner case which you do not need in your applications?
Could you give me a hint how to fix this?

Thank you!

**Comment by umjammer** [comment]
the original c source compares the calculated value and the bytes written,
then aborts when the comparison is failure.

https://github.com/shibatch/SSRC/blob/master/ssrc.c#L677

could you try to ignore when the calculated value is negative?
